package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conductor generated by hbm2java
 */
@Entity
@Table(name="conductor"
    ,schema="public"
)
public class Conductor  implements java.io.Serializable {


     private int idConductor;
     private String nombres;
     private String apellidos;
     private Integer licencia;
     private String sexo;
     private Integer telefono;
     private String direccion;
     private String observacion;
     private Set vehiculos = new HashSet(0);

    public Conductor() {
    }

	
    public Conductor(int idConductor) {
        this.idConductor = idConductor;
    }
    public Conductor(int idConductor, String nombres, String apellidos, Integer licencia, String sexo, Integer telefono, String direccion, String observacion, Set vehiculos) {
       this.idConductor = idConductor;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.licencia = licencia;
       this.sexo = sexo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.observacion = observacion;
       this.vehiculos = vehiculos;
    }
   
     @Id 
    
    @Column(name="idConductor", unique=true, nullable=false)
    public int getIdConductor() {
        return this.idConductor;
    }
    
    public void setIdConductor(int idConductor) {
        this.idConductor = idConductor;
    }
    
    @Column(name="nombres", length=20)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apellidos", length=20)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="licencia")
    public Integer getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(Integer licencia) {
        this.licencia = licencia;
    }
    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="direccion", length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="conductor")
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


