package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,schema="public"
)
public class Personal  implements java.io.Serializable {


     private int idPersonal;
     private String nombres;
     private String apellidos;
     private String email;
     private String usuario;
     private String clave;
     private String estado;
     private Date fechaCreacion;
     private String usuarioModificacion;
     private Date fechaModificacion;
     private Set paseos = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Personal(int idPersonal, String nombres, String apellidos, String email, String usuario, String clave, String estado, Date fechaCreacion, String usuarioModificacion, Date fechaModificacion, Set paseos) {
       this.idPersonal = idPersonal;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
       this.fechaCreacion = fechaCreacion;
       this.usuarioModificacion = usuarioModificacion;
       this.fechaModificacion = fechaModificacion;
       this.paseos = paseos;
    }
   
     @Id 
    
    @Column(name="idPersonal", unique=true, nullable=false)
    public int getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(int idPersonal) {
        this.idPersonal = idPersonal;
    }
    
    @Column(name="nombres", length=30)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apellidos", length=30)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="usuario", length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="clave", length=45)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_creacion", length=13)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usuario_modificacion", length=45)
    public String getUsuarioModificacion() {
        return this.usuarioModificacion;
    }
    
    public void setUsuarioModificacion(String usuarioModificacion) {
        this.usuarioModificacion = usuarioModificacion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha_modificacion", length=13)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personal")
    public Set getPaseos() {
        return this.paseos;
    }
    
    public void setPaseos(Set paseos) {
        this.paseos = paseos;
    }




}


