package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name="representante"
    ,schema="public"
)
public class Representante  implements java.io.Serializable {


     private BigDecimal idRepresentante;
     private String nombres;
     private String apelidos;
     private Date fechaNacimiento;
     private String email;
     private String sexo;
     private String direccion;
     private Integer telefono;
     private String profesion;
     private String observacion;

    public Representante() {
    }

	
    public Representante(BigDecimal idRepresentante) {
        this.idRepresentante = idRepresentante;
    }
    public Representante(BigDecimal idRepresentante, String nombres, String apelidos, Date fechaNacimiento, String email, String sexo, String direccion, Integer telefono, String profesion, String observacion) {
       this.idRepresentante = idRepresentante;
       this.nombres = nombres;
       this.apelidos = apelidos;
       this.fechaNacimiento = fechaNacimiento;
       this.email = email;
       this.sexo = sexo;
       this.direccion = direccion;
       this.telefono = telefono;
       this.profesion = profesion;
       this.observacion = observacion;
    }
   
     @Id 
    
    @Column(name="idRepresentante", unique=true, nullable=false, precision=131089, scale=0)
    public BigDecimal getIdRepresentante() {
        return this.idRepresentante;
    }
    
    public void setIdRepresentante(BigDecimal idRepresentante) {
        this.idRepresentante = idRepresentante;
    }
    
    @Column(name="nombres", length=10)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="apelidos", length=20)
    public String getApelidos() {
        return this.apelidos;
    }
    
    public void setApelidos(String apelidos) {
        this.apelidos = apelidos;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaNacimiento", length=13)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    @Column(name="email", length=20)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="direccion", length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="profesion", length=30)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


