package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Taller generated by hbm2java
 */
@Entity
@Table(name="taller"
    ,schema="public"
)
public class Taller  implements java.io.Serializable {


     private int idTaller;
     private String tema;
     private String duracion;
     private Date fecha;
     private String observacion;

    public Taller() {
    }

	
    public Taller(int idTaller) {
        this.idTaller = idTaller;
    }
    public Taller(int idTaller, String tema, String duracion, Date fecha, String observacion) {
       this.idTaller = idTaller;
       this.tema = tema;
       this.duracion = duracion;
       this.fecha = fecha;
       this.observacion = observacion;
    }
   
     @Id 
    
    @Column(name="idTaller", unique=true, nullable=false)
    public int getIdTaller() {
        return this.idTaller;
    }
    
    public void setIdTaller(int idTaller) {
        this.idTaller = idTaller;
    }
    
    @Column(name="tema", length=30)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    
    @Column(name="duracion", length=7)
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


