package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private long idUsuario;
     private String apellidos;
     private String nombres;
     private String grupo;
     private Long telefono;
     private String cedula;
     private Date fechaNacimiento;
     private Integer edad;
     private String email;
     private String sexo;
     private String tipoSangre;
     private String direccion;
     private String profesion;
     private String patologia;
     private String observacion;
     private String licenciaConducir;
     private String hijos;
     private String afiliado;

    public Usuario() {
    }

	
    public Usuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuario(long idUsuario, String apellidos, String nombres, String grupo, Long telefono, String cedula, Date fechaNacimiento, Integer edad, String email, String sexo, String tipoSangre, String direccion, String profesion, String patologia, String observacion, String licenciaConducir, String hijos, String afiliado) {
       this.idUsuario = idUsuario;
       this.apellidos = apellidos;
       this.nombres = nombres;
       this.grupo = grupo;
       this.telefono = telefono;
       this.cedula = cedula;
       this.fechaNacimiento = fechaNacimiento;
       this.edad = edad;
       this.email = email;
       this.sexo = sexo;
       this.tipoSangre = tipoSangre;
       this.direccion = direccion;
       this.profesion = profesion;
       this.patologia = patologia;
       this.observacion = observacion;
       this.licenciaConducir = licenciaConducir;
       this.hijos = hijos;
       this.afiliado = afiliado;
    }
   
     @Id 
    
    @Column(name="idUsuario", unique=true, nullable=false, precision=10, scale=0)
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="apellidos", length=30)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="nombres", length=30)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="grupo", length=10)
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    
    @Column(name="telefono", precision=10, scale=0)
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="cedula", length=10)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaNacimiento", length=13)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    
    @Column(name="edad")
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="tipoSangre", length=3)
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    
    @Column(name="direccion", length=50)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="profesion", length=50)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    
    @Column(name="patologia")
    public String getPatologia() {
        return this.patologia;
    }
    
    public void setPatologia(String patologia) {
        this.patologia = patologia;
    }
    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    
    @Column(name="licenciaConducir", length=2)
    public String getLicenciaConducir() {
        return this.licenciaConducir;
    }
    
    public void setLicenciaConducir(String licenciaConducir) {
        this.licenciaConducir = licenciaConducir;
    }
    
    @Column(name="hijos", length=2)
    public String getHijos() {
        return this.hijos;
    }
    
    public void setHijos(String hijos) {
        this.hijos = hijos;
    }
    
    @Column(name="afiliado", length=2)
    public String getAfiliado() {
        return this.afiliado;
    }
    
    public void setAfiliado(String afiliado) {
        this.afiliado = afiliado;
    }




}


