package model;
// Generated Jun 26, 2013 11:41:45 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,schema="public"
)
public class Vehiculo  implements java.io.Serializable {


     private int idVehiculo;
     private Conductor conductor;
     private String tipoVehiculo;
     private Integer capacidad;
     private String observacion;

    public Vehiculo() {
    }

	
    public Vehiculo(int idVehiculo, Conductor conductor) {
        this.idVehiculo = idVehiculo;
        this.conductor = conductor;
    }
    public Vehiculo(int idVehiculo, Conductor conductor, String tipoVehiculo, Integer capacidad, String observacion) {
       this.idVehiculo = idVehiculo;
       this.conductor = conductor;
       this.tipoVehiculo = tipoVehiculo;
       this.capacidad = capacidad;
       this.observacion = observacion;
    }
   
     @Id 
    
    @Column(name="idVehiculo", unique=true, nullable=false)
    public int getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(int idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVehiculo", unique=true, nullable=false, insertable=false, updatable=false)
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    
    @Column(name="tipoVehiculo", length=15)
    public String getTipoVehiculo() {
        return this.tipoVehiculo;
    }
    
    public void setTipoVehiculo(String tipoVehiculo) {
        this.tipoVehiculo = tipoVehiculo;
    }
    
    @Column(name="capacidad")
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    
    @Column(name="observacion")
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }




}


