package modelos;
// Generated Jun 26, 2013 5:38:42 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name="menu"
    ,catalog="basecgam"
)
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private int menuId;
     private int nivel;
     private int orden;
     private String nombre;
     private String uri;
     private String icono;
     private byte estado;

    public Menu() {
    }

    public Menu(int menuId, int nivel, int orden, String nombre, String uri, String icono, byte estado) {
       this.menuId = menuId;
       this.nivel = nivel;
       this.orden = orden;
       this.nombre = nombre;
       this.uri = uri;
       this.icono = icono;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_Menu", unique=true, nullable=false)
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    
    @Column(name="menu_id", nullable=false)
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }
    
    @Column(name="Nivel", nullable=false)
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    
    @Column(name="Orden", nullable=false)
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    
    @Column(name="Nombre", nullable=false, length=80)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="Uri", nullable=false, length=120)
    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }
    
    @Column(name="Icono", nullable=false, length=30)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    
    @Column(name="Estado", nullable=false)
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }




}


