package modelos;
// Generated Jun 26, 2013 5:38:42 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="basecgam"
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombres;
     private String apellidos;
     private String codigo;
     private String grupo;
     private String telefono;
     private String cedula;
     private String edad;
     private String correo;
     private String sexo;
     private String tipoSangre;
     private String direccion;
     private String profesion;
     private String convivencia;
     private String patologia;
     private String alergia;
     private String instruccion;
     private boolean licencia;
     private String hijos;
     private boolean afiliado;
     private String observaciones;

    public Usuario() {
    }

    public Usuario(String nombres, String apellidos, String codigo, String grupo, String telefono, String cedula, String edad, String correo, String sexo, String tipoSangre, String direccion, String profesion, String convivencia, String patologia, String alergia, String instruccion, boolean licencia, String hijos, boolean afiliado, String observaciones) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.codigo = codigo;
       this.grupo = grupo;
       this.telefono = telefono;
       this.cedula = cedula;
       this.edad = edad;
       this.correo = correo;
       this.sexo = sexo;
       this.tipoSangre = tipoSangre;
       this.direccion = direccion;
       this.profesion = profesion;
       this.convivencia = convivencia;
       this.patologia = patologia;
       this.alergia = alergia;
       this.instruccion = instruccion;
       this.licencia = licencia;
       this.hijos = hijos;
       this.afiliado = afiliado;
       this.observaciones = observaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_Usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    
    @Column(name="Nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="Apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="Codigo", nullable=false, length=4)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    
    @Column(name="Grupo", nullable=false, length=45)
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    
    @Column(name="Telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="Cedula", nullable=false, length=10)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    
    @Column(name="Edad", nullable=false, length=2)
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    
    @Column(name="Correo", nullable=false, length=45)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    @Column(name="Sexo", nullable=false, length=9)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="Tipo_Sangre", nullable=false, length=2)
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="Profesion", nullable=false, length=45)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    
    @Column(name="Convivencia", nullable=false, length=10)
    public String getConvivencia() {
        return this.convivencia;
    }
    
    public void setConvivencia(String convivencia) {
        this.convivencia = convivencia;
    }
    
    @Column(name="Patologia", nullable=false, length=45)
    public String getPatologia() {
        return this.patologia;
    }
    
    public void setPatologia(String patologia) {
        this.patologia = patologia;
    }
    
    @Column(name="Alergia", nullable=false, length=45)
    public String getAlergia() {
        return this.alergia;
    }
    
    public void setAlergia(String alergia) {
        this.alergia = alergia;
    }
    
    @Column(name="Instruccion", nullable=false, length=45)
    public String getInstruccion() {
        return this.instruccion;
    }
    
    public void setInstruccion(String instruccion) {
        this.instruccion = instruccion;
    }
    
    @Column(name="Licencia", nullable=false)
    public boolean isLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(boolean licencia) {
        this.licencia = licencia;
    }
    
    @Column(name="Hijos", nullable=false, length=1)
    public String getHijos() {
        return this.hijos;
    }
    
    public void setHijos(String hijos) {
        this.hijos = hijos;
    }
    
    @Column(name="Afiliado", nullable=false)
    public boolean isAfiliado() {
        return this.afiliado;
    }
    
    public void setAfiliado(boolean afiliado) {
        this.afiliado = afiliado;
    }
    
    @Column(name="Observaciones", nullable=false, length=45)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


