package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conductor generated by hbm2java
 */
@Entity
@Table(name="conductor"
    ,catalog="basesoftware"
)
public class Conductor  implements java.io.Serializable {


     private Integer idConductor;
     private String nombres;
     private String apellidos;
     private String licencia;
     private String sexo;
     private String telefono;
     private String direccion;
     private String observacion;
     private Set vehiculos = new HashSet(0);

    public Conductor() {
    }

	
    public Conductor(String nombres, String apellidos, String licencia, String sexo, String telefono, String direccion, String observacion) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.licencia = licencia;
        this.sexo = sexo;
        this.telefono = telefono;
        this.direccion = direccion;
        this.observacion = observacion;
    }
    public Conductor(String nombres, String apellidos, String licencia, String sexo, String telefono, String direccion, String observacion, Set vehiculos) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.licencia = licencia;
       this.sexo = sexo;
       this.telefono = telefono;
       this.direccion = direccion;
       this.observacion = observacion;
       this.vehiculos = vehiculos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idConductor", unique=true, nullable=false)
    public Integer getIdConductor() {
        return this.idConductor;
    }
    
    public void setIdConductor(Integer idConductor) {
        this.idConductor = idConductor;
    }
    
    @Column(name="Nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="Apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="Licencia", nullable=false, length=2)
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }
    
    @Column(name="Sexo", nullable=false, length=2)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="Telefono", nullable=false, length=45)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="Direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="Observacion", nullable=false, length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="conductor")
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


