package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
    ,catalog="basesoftware"
)
public class Personal  implements java.io.Serializable {


     private Integer idPersonal;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String usuario;
     private String clave;
     private String estado;
     private String email;
     private Date fechaCreacion;
     private String usaurioModificacion;
     private Date fechaModificacion;

    public Personal() {
    }

	
    public Personal(Rol rol, String nombre, String apellido, String usuario, String clave, String email) {
        this.rol = rol;
        this.nombre = nombre;
        this.apellido = apellido;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
    }
    public Personal(Rol rol, String nombre, String apellido, String usuario, String clave, String estado, String email, Date fechaCreacion, String usaurioModificacion, Date fechaModificacion) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
       this.email = email;
       this.fechaCreacion = fechaCreacion;
       this.usaurioModificacion = usaurioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPersonal", unique=true, nullable=false)
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="apellido", nullable=false, length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="clave", nullable=false, length=45)
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    
    @Column(name="estado", length=45)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="usaurio_modificacion", length=45)
    public String getUsaurioModificacion() {
        return this.usaurioModificacion;
    }
    
    public void setUsaurioModificacion(String usaurioModificacion) {
        this.usaurioModificacion = usaurioModificacion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modificacion", length=19)
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


