package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,catalog="basesoftware"
)
public class Vehiculo  implements java.io.Serializable {


     private Integer idVehiculo;
     private Conductor conductor;
     private String tipo;
     private String capacidad;
     private String observacion;
     private Set paseos = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(Conductor conductor, String tipo, String capacidad, String observacion) {
        this.conductor = conductor;
        this.tipo = tipo;
        this.capacidad = capacidad;
        this.observacion = observacion;
    }
    public Vehiculo(Conductor conductor, String tipo, String capacidad, String observacion, Set paseos) {
       this.conductor = conductor;
       this.tipo = tipo;
       this.capacidad = capacidad;
       this.observacion = observacion;
       this.paseos = paseos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idVehiculo", unique=true, nullable=false)
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conductor_n", nullable=false)
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    
    @Column(name="Tipo", nullable=false, length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="Capacidad", nullable=false, length=45)
    public String getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(String capacidad) {
        this.capacidad = capacidad;
    }
    
    @Column(name="Observacion", nullable=false, length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set getPaseos() {
        return this.paseos;
    }
    
    public void setPaseos(Set paseos) {
        this.paseos = paseos;
    }




}


