package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Asistencia generated by hbm2java
 */
@Entity
@Table(name="asistencia"
    ,catalog="basesoftware"
)
public class Asistencia  implements java.io.Serializable {


     private Integer idAsistencia;
     private Usuario usuario;
     private int numero;
     private Date fecha;

    public Asistencia() {
    }

    public Asistencia(Usuario usuario, int numero, Date fecha) {
       this.usuario = usuario;
       this.numero = numero;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAsistencia", unique=true, nullable=false)
    public Integer getIdAsistencia() {
        return this.idAsistencia;
    }
    
    public void setIdAsistencia(Integer idAsistencia) {
        this.idAsistencia = idAsistencia;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user1", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="Numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


