package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Paseo generated by hbm2java
 */
@Entity
@Table(name="paseo"
    ,catalog="basesoftware"
)
public class Paseo  implements java.io.Serializable {


     private Integer idPaseo;
     private Vehiculo vehiculo;
     private Usuario usuario;
     private String tema;
     private int capacidad;
     private int duracion;

    public Paseo() {
    }

    public Paseo(Vehiculo vehiculo, Usuario usuario, String tema, int capacidad, int duracion) {
       this.vehiculo = vehiculo;
       this.usuario = usuario;
       this.tema = tema;
       this.capacidad = capacidad;
       this.duracion = duracion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPaseo", unique=true, nullable=false)
    public Integer getIdPaseo() {
        return this.idPaseo;
    }
    
    public void setIdPaseo(Integer idPaseo) {
        this.idPaseo = idPaseo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vehiculo", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_user", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="Tema", nullable=false, length=45)
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    
    @Column(name="Capacidad", nullable=false)
    public int getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(int capacidad) {
        this.capacidad = capacidad;
    }
    
    @Column(name="Duracion", nullable=false)
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


