package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name="representante"
    ,catalog="basesoftware"
)
public class Representante  implements java.io.Serializable {


     private Integer idRepresentante;
     private String nombres;
     private String apellidos;
     private int edad;
     private String email;
     private String sexo;
     private String profesion;
     private String observacion;
     private Set usuarios = new HashSet(0);

    public Representante() {
        this.idRepresentante=0;
    }

	
    public Representante(String nombres, String apellidos, int edad, String email, String sexo, String profesion, String observacion) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.edad = edad;
        this.email = email;
        this.sexo = sexo;
        this.profesion = profesion;
        this.observacion = observacion;
    }
    public Representante(String nombres, String apellidos, int edad, String email, String sexo, String profesion, String observacion, Set usuarios) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.email = email;
       this.sexo = sexo;
       this.profesion = profesion;
       this.observacion = observacion;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRepresentante", unique=true, nullable=false)
    public Integer getIdRepresentante() {
        return this.idRepresentante;
    }
    
    public void setIdRepresentante(Integer idRepresentante) {
        this.idRepresentante = idRepresentante;
    }
    
    @Column(name="Nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    
    @Column(name="Apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    
    @Column(name="Edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    
    @Column(name="Email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="Sexo", nullable=false, length=10)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    
    @Column(name="Profesion", nullable=false, length=45)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    
    @Column(name="Observacion", nullable=false, length=45)
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="representante")
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


