package modelos;
// Generated Jul 6, 2013 9:19:58 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rolmenu generated by hbm2java
 */
@Entity
@Table(name="rolmenu"
    ,catalog="basesoftware"
)
public class Rolmenu  implements java.io.Serializable {


     private Integer idRolMenu;
     private Rol rol;
     private Menu menu;

    public Rolmenu() {
    }

    public Rolmenu(Rol rol, Menu menu) {
       this.rol = rol;
       this.menu = menu;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idRolMenu", unique=true, nullable=false)
    public Integer getIdRolMenu() {
        return this.idRolMenu;
    }
    
    public void setIdRolMenu(Integer idRolMenu) {
        this.idRolMenu = idRolMenu;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_rol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_menu", nullable=false)
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }




}


