package model;
// Generated Aug 15, 2013 12:45:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer idPersonal;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String usuario;
     private String clave;
     private String estado;
     private String email;
     private Date fechaCreacion;
     private String usaurioModificacion;
     private Date fechaModificacion;

    public Personal() {
    }

	
    public Personal(Rol rol, String nombre, String apellido, String usuario, String clave, String email) {
        this.rol = rol;
        this.nombre = nombre;
        this.apellido = apellido;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
    }
    public Personal(Rol rol, String nombre, String apellido, String usuario, String clave, String estado, String email, Date fechaCreacion, String usaurioModificacion, Date fechaModificacion) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.usuario = usuario;
       this.clave = clave;
       this.estado = estado;
       this.email = email;
       this.fechaCreacion = fechaCreacion;
       this.usaurioModificacion = usaurioModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdPersonal() {
        return this.idPersonal;
    }
    
    public void setIdPersonal(Integer idPersonal) {
        this.idPersonal = idPersonal;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsaurioModificacion() {
        return this.usaurioModificacion;
    }
    
    public void setUsaurioModificacion(String usaurioModificacion) {
        this.usaurioModificacion = usaurioModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


